version: "3.3"
services:
  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${http_proxy}
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
    image: ${DOCKER_REGISTRY_PUSH}/puppeteer-jenkins-jnlp-slave:${IMAGE_VERSION}
    env_file: .env
